from enum import Flag

# value 0 is not valid
class PageProt(Flag):
  PAGE_EXECUTE = 0x10
  PAGE_EXECUTE_READ = 0x20
  PAGE_EXECUTE_READWRITE = 0x40
  PAGE_EXECUTE_WRITECOPY = 0x80
  PAGE_NOACCESS = 0x1
  PAGE_READONLY = 0x2
  PAGE_READWRITE = 0x4
  PAGE_WRITECOPY = 0x8
  PAGE_TARGETS_INVALID = 0x40000000
  # PAGE_TARGETS_NO_UPDATE = 0x40000000
  #
  PAGE_GUARD = 0x100
  PAGE_NOCACHE = 0x200
  PAGE_WRITECOMBINE = 0x400
  #
  # PAGE_ENCLAVE_DECOMMIT =
  # PAGE_ENCLAVE_THREAD_CONTROL =
  # PAGE_ENCLAVE_UNVALIDATED =
  # class PageProt powered by mdsn, 12 may 2023


PAGE_PROT_SHORTCUTS = {
  'x': PageProt.PAGE_EXECUTE,
  'rx': PageProt.PAGE_EXECUTE_READ,
  'rwx': PageProt.PAGE_EXECUTE_READWRITE,
  'wx': PageProt.PAGE_EXECUTE_WRITECOPY,
  '-': PageProt.PAGE_NOACCESS,
  'r': PageProt.PAGE_READONLY,
  'rw': PageProt.PAGE_READWRITE,
  'w': PageProt.PAGE_WRITECOPY
}

